name: Deploy React app to GitHub Pages

on:
  push:
    branches:
      - master  # Cambia a 'main' si tu rama principal es 'main'
  workflow_dispatch:  # Permite ejecutar manualmente desde la pestaña Actions

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instala las dependencias
      - name: Install dependencies
        run: npm install

      # Deshabilita el tratamiento de los warnings como errores
      - name: Disable CI for warnings
        run: echo "CI=false" >> $GITHUB_ENV

      # Configura la identidad de Git para el despliegue
      - name: Set Git identity
        run: |
          git config --global user.name "Johnkl725"
          git config --global user.email "john.castillo1@unmsm.edu.pe"

      # Construye la aplicación React
      - name: Build the app
        run: npm run build

      # Configura la página de GitHub Pages y despliega
      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages --save-dev  # Instala gh-pages para el despliegue
          npm run deploy                  # Despliega la aplicación a GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
